# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DATA_FILE": "88_app.ipynb",
         "AUTHOR_INFO": "88_app.ipynb",
         "APP_NAME": "88_app.ipynb",
         "SideBar": "88_app.ipynb",
         "create_sidebar": "88_app.ipynb",
         "create_mainscreen": "88_app.ipynb",
         "load_walk_data": "88_app.ipynb",
         "sb": "88_app.ipynb"}

modules = ["app.py"]

doc_url = "https://mjboothaus.github.io/emmaus_walking/"

git_url = "https://github.com/mjboothaus/emmaus_walking/tree/master/"

def custom_doc_links(name): return None
