source "https://rubygems.org"

gem 'github-pages', '>= 214', group: :jekyll_plugins

# Added at 2019-11-25 10:11:40 -0800 by jhoward:
gem "nokogiri", "< 1.11.5"
gem "jekyll", ">= 3.9.0"
gem "kramdown", ">= 2.3.1"
gem "jekyll-remote-theme", ">= 0.4.3"
