# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"in_notebook": "00_core.ipynb",
         "ipython_info": "00_core.ipynb",
         "calc_walk_stats": "01_datapipe.ipynb",
         "load_and_cache_raw_walk_data": "01_datapipe.ipynb",
         "load_config_file": "88_app.ipynb",
         "APP_CONFIG_FILE": "88_app.ipynb",
         "app_config": "88_app.ipynb",
         "APP_NAME": "88_app.ipynb",
         "CACHED_WALK_DATA": "88_app.ipynb",
         "plot_walk": "88_app.ipynb",
         "plot_entire_walk": "88_app.ipynb",
         "plot_walk_points": "88_app.ipynb",
         "SideBar": "88_app.ipynb",
         "app_sidebar": "88_app.ipynb",
         "IMAGE_PATH": "88_app.ipynb",
         "WALK_NAME": "88_app.ipynb",
         "load_cached_walking_data": "88_app.ipynb",
         "app_mainscreen": "88_app.ipynb",
         "notebook_mainscreen": "88_app.ipynb",
         "sb": "88_app.ipynb",
         "get_project_root": "00_core.ipynb"}

modules = ["core.py",
           "datapipe.py",
           "app.py"]

doc_url = "https://mjboothaus.github.io/emmaus_walking/"

git_url = "https://github.com/mjboothaus/emmaus_walking/tree/master/"

def custom_doc_links(name): return None
