# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['in_notebook', 'ipython_info', 'get_project_root']

# Cell
from pathlib import Path
import sys

# Cell

def in_notebook() -> bool:
    """
    Returns ``True`` if the module is running in IPython kernel,
    ``False`` if in IPython shell or other Python shell.
    """
    return "ipykernel" in sys.modules


# later I found out this:


def ipython_info():
    ip = False
    if "ipykernel" in sys.modules:
        ip = "notebook"
    elif "IPython" in sys.modules:
        ip = "terminal"
    return ip


# Cell
def get_project_root() -> Path:
    if not in_notebook():
        return Path(__file__).parent
    else:
        return Path.cwd().parent



# Cell

get_project_root()